name: Build Production

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+  # Semver Release

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with: 
          submodules: 'recursive'
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hub.opensciencegrid.org/macrostrat/web
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=sha-{{sha}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to OSG DockerHub
        uses: docker/login-action@v2
        with:
          registry: hub.opensciencegrid.org
          username: ${{ vars.HARBOR_CLI_NAME }}
          password: ${{ secrets.HARBOR_CLI_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            VITE_MAPBOX_API_TOKEN=${{ secrets.MAPBOX_API_TOKEN }}
            VITE_MACROSTRAT_TILESERVER_V1=https://tiles.macrostrat.org
            VITE_MACROSTRAT_TILESERVER_DOMAIN=https://tileserver.macrostrat-dev.chtc.io/
            VITE_MACROSTRAT_API_DOMAIN=
            VITE_CORELLE_API_DOMAIN=https://rotate.macrostrat.org
            PUBLIC_URL=/map/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
